# Generated by Django 5.0.1 on 2024-01-16 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type_name', models.CharField(help_text='Enter the type of card (debit, credit, etc.)', max_length=10, unique=True)),
            ],
            options={
                'ordering': ['card_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Enter a category (restaurant, transport, etc.)', max_length=50, unique=True)),
                ('category_logo', models.ImageField(blank=True, help_text='Upload category logo', null=True, upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50)),
                ('phone', models.CharField(help_text='Enter your phone number', max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Enter your photo', null=True, upload_to='')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text='Enter entity name', max_length=50, unique=True)),
                ('entity_logo', models.ImageField(blank=True, help_text='Upload entity logo', null=True, upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['entity_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type_name', models.CharField(help_text='Enter the type of project (trip, vacation, etc.)', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['project_type_name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type_name', models.CharField(help_text='Enter the type of transaction (income, expense, etc.)', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['transaction_type_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_name', models.CharField(help_text='Enter the type of account (savings, investing, etc.)', max_length=20, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_type_name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(help_text='Enter account IBAN', max_length=24, unique=True, verbose_name='IBAN')),
                ('account_alias', models.CharField(blank=True, help_text='Enter account alias', max_length=20, null=True)),
                ('balance', models.FloatField()),
                ('currency', models.CharField(help_text='Enter account currency', max_length=3)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movements.accounttype')),
                ('customers', models.ManyToManyField(to='movements.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movements.entity')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_alias', models.CharField(blank=True, help_text='Enter card name', max_length=30, null=True)),
                ('card_number', models.CharField(help_text='Enter card number', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator])),
                ('expiration_date', models.DateField(help_text='Enter expiration date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.account')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movements.cardtype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.customer')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter project name', max_length=50)),
                ('project_description', models.TextField(blank=True, help_text='Enter project description', null=True)),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movements.projecttype')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(help_text='Enter a subcategory', max_length=50, unique=True)),
                ('subcategory_logo', models.ImageField(blank=True, help_text='Upload subcategory logo', null=True, upload_to='', verbose_name='Logo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'order_with_respect_to': 'category',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Transaction concept', max_length=200)),
                ('operation_date', models.DateField()),
                ('value_date', models.DateField()),
                ('amount', models.FloatField(help_text='Transaction amount')),
                ('currency', models.CharField(help_text='Enter transaction currency', max_length=3)),
                ('transaction_comment', models.CharField(blank=True, help_text='Enter any comments here', max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movements.account')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movements.card')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movements.project')),
                ('referenced_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movements.transaction')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movements.subcategory')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movements.transactiontype')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
