# Generated by Django 5.0.1 on 2024-01-17 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='accounttype',
            old_name='account_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='cardtype',
            old_name='card_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='entity_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='transaction_type_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_logo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='entity_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='project_type_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_logo',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_name',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload category logo', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, help_text='Enter a category (restaurant, transport, etc.)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload entity logo', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Enter project description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='name',
            field=models.CharField(default=1, help_text='Enter the type of project (trip, vacation, etc.)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload subcategory logo', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=1, help_text='Enter a subcategory', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
