# Generated by Django 4.2.8 on 2024-01-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_remove_projecttype_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
