# Generated by Django 4.2.8 on 2024-01-17 22:38

from django.db import migrations, models
import movements.models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0004_remove_account_owner_remove_card_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload category logo', null=True, upload_to=movements.models.category_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Enter your photo', null=True, upload_to=movements.models.customer_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload entity logo', null=True, upload_to=movements.models.entity_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload subcategory logo', null=True, upload_to=movements.models.subcategory_logo_upload_path),
        ),
    ]
