# Generated by Django 4.2.8 on 2024-01-21 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movements', '0007_account_owner_card_owner_category_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(help_text='Enter account IBAN', max_length=24, verbose_name='IBAN'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('iban', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('number', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttype',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'owner')},
        ),
    ]
